name: AutoFireworkRegions
version: 2.0
main: me.flexcraft.autofirework.AutoFireworkRegions
api-version: 1.20
depend: [WorldGuard]
author: Helfy_YT
description: Auto fireworks inside WorldGuard regions
